### ISSUE TITLE
[Circle-CI] Haxe installation

### ISSUE THREAD

**Issue by Mariosyian** [Mariosyian/benchmarking-programming-languages#16]
Since Haxe does not have a CircleCI image to be loaded, the language needs to be manually installed and run each time the CI is run.
Haxe helpfully provides a direct GitHub release of the Haxe language binaries. These can be downloaded and extracted, but still need to be linked.

This is what is run until now
```
haxe:
    docker:
        - image: cimg/base:2021.12
    steps:
        - checkout
        - run: wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.4/haxe-4.2.4-linux64.tar.gz
        - run: tar xfvz haxe-4.2.4-linux64.tar.gz
        - run: wget https://github.com/HaxeFoundation/neko/releases/download/v2-3-0/neko-2.3.0-linux64.tar.gz
        - run: tar xfvz neko-2.3.0-linux64.tar.gz
        - run: sudo ln -s $(pwd)/neko-2.3.0-linux64/neko /bin/neko
        - run: haxe_20211022152000_ab0c054/haxelib install utest
        - run: haxe_20211022152000_ab0c054/haxelib install formatter
        - run: echo "Checking formatting, compiling, building, and testing ..."
        - run: ./circleCI.sh --haxe
```
The `neko` build is what's causing most of the issues as that needs to be installed for `haxe` to even run.
